#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: demo1-4
  cloud:
    zookeeper:
      connect-string: 116.62.141.102:2181
  thymeleaf:
    refix: classpath:/templates/

